### ISSUE TITLE
better scoped styles 

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#406]
```css
   input[type=checkbox] {
        display: none;
    }

    li p {
        display: none;
    }

    input[type=checkbox]:checked + label ~ p {
        display: block;
    }
```
