### ISSUE TITLE
Scoped styles doesn't work for dynamic class

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#532]
```html
<div class="{'ui ' + (type ? type : '') + ' breadcrumb'}">
  <a class="section" href="{root}">Start</a>
  <a class="section" href="{route('tools')}"><translate tools /></a>
</div>
```
Scoped styles are ignored
```css
<style scoped>
.ui.breadcrumb a.section { margin-right: 15px }
.ui.breadcrumb a.section:last-child { margin-right: 0 }
.ui.gray.breadcrumb a { color: #808080 }
.ui.gray.breadcrumb a:hover { color: #C0C0C0 }
</style>
```
