### ISSUE TITLE
Scoped styles are ignored

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#534]
```html
<import grid from="./components/grid.html"/>
<import row from="./components/row.html"/>
<import icon from="./components/icon.html"/>
<import form from="./components/form.html"/>
<import input from="./components/input.html"/>
<div class="message">
  <icon name="warning" width="40"/> 
  <if status eq="{404}">
    <h4><translate 404.title/></h4>
    <p><translate 404.subtitle/><br></p>
    <form>
      <grid stackable>
        <row>
          <div class="column">
            <input placeholder|translate="enter"/>
          </div>
        </row>
        <row>
          <div class="column">
            <p><translate back/><a href="/"><translate homepage/></a></p>
          </div>
        </row>
      </grid>
    </form>
  </if>
  <elseif status eq="{403}">
    <h4><translate 403.title/></h4>
    <p><translate return/><a href="/"><translate homepage/></a><space/><translate contact/> </p>
  </elseif>
  <else>
    <h4><translate 500.title/></h4>
    <p><translate 500.subtitle/><br><translate try.again/></p>
  </else>
</div>
<if imgPath>
  <img class="status" src="{imgPath}"/>
</if>
```
```css
<style scoped>
.message {
  text-align: center;
  z-index: 1000;
  height: 300px;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
}
.status {
  position: absolute;
  left: 0;
  right: 0;
  margin: 0 auto;
  bottom: 100px;
  width: 100%;
  max-width: 700px;
  min-width: 300px;
  z-index: -100000;
}
.ui.form {
  width: 100%;
  max-width: 400px;
}
```

Latest condition `<if imgPath>` causes that scoped styles are not applied to the html tags
